version: 2
jobs:
  unit-testing:
    working_directory: ~/src/github.com/hybridtheory/iab-tcf
    docker:
      - image: golang:1.21-bullseye
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-go-dependencies-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run:
          name: Install test framework
          command: |
            go install github.com/onsi/ginkgo/v2/ginkgo
            go install github.com/onsi/gomega/...
      - run:
          name: Running Unit Tests
          command: |
            ginkgo --race -cover --junit-report=junit.xml --output-dir=./test-reports ./...
      - run:
          name: Generate code coverage
          command: |
            go tool cover -html=./test-reports/coverprofile.out -o ./test-reports/coverage.html
      - store_artifacts:
          path: ./test-reports/
          destination: artifacts
      - store_test_results:
          path: test-reports
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: v1-go-dependencies-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run:
          name: codacy coverage
          command: |
            export CODACY_PROJECT_NAME=iab-tcf
            bash <(curl -Lks https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r ./test-reports/coverprofile.out

workflows:
  version: 2
  iab-tcf:
    jobs:
      - unit-testing
